Add sass package
When trying to run NRPTI locally got runtime error (below).  Added sass package to fix it.

[start:public-lng  ] ERROR in ./src/styles.scss (/Users/dkorin/Projects/Sustainment/NRPTI/NRPTI/angular/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!/Users/dkorin/Projects/Sustainment/NRPTI/NRPTI/angular/node_modules/postcss-loader/src??embedded!/Users/dkorin/Projects/Sustainment/NRPTI/NRPTI/angular/node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
[start:public-lng  ] Module build failed (from /Users/dkorin/Projects/Sustainment/NRPTI/NRPTI/angular/node_modules/sass-loader/lib/loader.js):
[start:public-lng  ] Error: Cannot find module 'node-sass'
[start:public-lng  ] Require stack: